### ISSUE TITLE
Use SDM630 Modbus with API simulator

### ISSUE THREAD

**Issue by miroslavpetrov** [DCSBL/homewizard-energy-api-sim#1]
Hello,

I already have a SDM630 but with Modbus over RS485. Can I use your simulator to get the readings via RS485 and view them in the homewizard app?

**Comment by DCSBL** [comment]
Interesting question. But no, it is not possible.

The simulation is intended for developing applications that make use of the local API without using or having a physical device. What you are asking is something completely different:

- This tool does not use Modbus, but an API that is developed by HomeWizard.
- The HomeWizard Energy app and cloud uses a different technology, the API is only available for local stuff.

It _is_ possible to make something with Modbus and hook it up to something you can control (like Home Assistant), but you can't pass this data to the HomeWizard app. That is why the SDM630-wifi exists.

**Comment by miroslavpetrov** [comment]
Thank you for your answer. I saw the SDM630-wifi but it is not the model that supports CTs. My load is around 300-400A(very big machine :D) and I use 500A:5A CTs. I will find a different way. I just liked the UI of homewizzard energy.
